name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: STAGINGGG
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY_STAGING }}" > private_key
        cat private_key
        chmod 600 private_key
        ssh-keyscan -t ed25519 -H ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts

    - name: SSH into AWS Instance
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.USER_NAME }}@${{ secrets.HOSTNAME }} '
          bash trigger_service_up.sh
          echo "THE SERVER IS UP AT http://${{ secrets.HOSTNAME }}"'
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
