name: EC2 Command Execution

on:
  push:
    branches:
      - main

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: appleboy/ssh-action@master
      with:
        private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY_STAGING }}

    - name: Run Command on EC2
      run: |
        EC2_IP=$(ssh -o StrictHostKeyChecking=no ubuntu@57.180.56.137 "bash -s" < ~/trigger_service_up.sh)
        echo "You Can Access the Site at : http://57.180.56.137"
