name: EC2 Command Execution

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 STAGING
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build & Deploy
        run: echo ${{ secrets.SSH_PRIVATE_KEY_STAGING }}