name: EC2 Command Execution

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 STAGING
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          HOSTNAME: ${{ secrets.SSH_HOST_STAGinG }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          sudo cat private_key